id: P008104
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 13:01:48.916166
source_metadata:
  id: bdr:W6394
  title: གཙུག་ཏོར་དྲི་མེད་ལྷ་ལྔའི་སྒྲུབ་དཀྱིལ་སློབ་མ་རྗེས་འཛིན།
  author: ''
  volumes:
    a2add505672643a0b3355e60e3101459:
      image_group_id: I1KG9092
      title: Volume 1 of gtsug tor dri med lha lnga'i sgrub dkyil slob ma rjes 'dzin
      volume_number: 1
      total_pages: 62
      basefile: v001.txt
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
