id: P008104
initial_creation_type: ocr
source_metadata:
  id: bdr:W6394
  title: གཙུག་ཏོར་དྲི་མེད་ལྷ་ལྔའི་སྒྲུབ་དཀྱིལ་སློབ་མ་རྗེས་འཛིན།
  author: ''
  volumes:
    5c2982fcc5074863a0853378ef8f48a1:
      image_group_id: I1KG9092
      title: ''
      volume_number: 1
      total_pages: 62
ebook_metadata:
  title: གཙུག་ཏོར་དྲི་མེད་ལྷ་ལྔའི་སྒྲུབ་དཀྱིལ་སློབ་མ་རྗེས་འཛིན།
  author: ''
  sku: P008104
  cover: cover.jpg
  layers:
  - pagination
