id: IE5FEB349
legacy_id: P008104
ocr_import_info:
  bdrc_scan_id: W6394
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T00:25:07'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T03:08:31.745970+00:00'
last_modified: 2022-09-04 11:08:37.149410
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W6394
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW6394
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གཙུག་ཏོར་དྲི་མེད་ལྷ་ལྔའི་སྒྲུབ་དཀྱིལ་སློབ་མ་རྗེས་འཛིན།
  author: བྲག་རི་དམ་ཚིག་རྡོ་རྗེ།
statistics:
  ocr_word_mean_confidence_index: 0.7283417382758427
  ocr_word_median_confidence_index: 0.7900000214576721
quality: null
bases:
  I1KG9092:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG9092
      total_pages: 62
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG9092.txt
    statistics:
      ocr_word_median_confidence_index: 0.7900000214576721
      ocr_word_mean_confidence_index: 0.7283417382758427
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
