id: IE5FEB349
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T00:25:35+00:00'
last_modified: '2022-06-09T04:31:27.182339+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W6394
  title: གཙུག་ཏོར་དྲི་མེད་ལྷ་ལྔའི་སྒྲུབ་དཀྱིལ་སློབ་མ་རྗེས་འཛིན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4743':
      image_group_id: I1KG9092
      title: Volume 1 of gtsug tor dri med lha lnga'i sgrub dkyil slob ma rjes 'dzin
      total_pages: 62
      order: 1
      base_file: 4743.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
